apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-metastore
data:
  metastore-site.xml: |-
    <configuration>
        <property>
            <name>metastore.task.threads.always</name>
            <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask</value>
        </property>
        <property>
            <name>metastore.expression.proxy</name>
            <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
        </property>
        <property>
            <name>metastore.thrift.uris</name>
            <value>thrift://0.0.0.0:9083</value>
            <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>{{ .Values.mysql.jdbcUrl }}/{{ .Values.mysql.dbName }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>com.mysql.cj.jdbc.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>{{ .Values.mysql.user }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>{{ .Values.mysql.password }}</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
        <property>
            <name>fs.s3a.impl</name>
            <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
            <property>
            <name>metastore.warehouse.dir</name>
            <value>s3a://{{ .Values.s3.warehouseBucket }}/warehouse/</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>{{ .Values.s3.endpoint }}</value>
        </property>
        <property>
            <name>fs.s3a.access.key</name>
            <value>{{ .Values.s3.accessKey }}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>{{ .Values.s3.secretKey }}</value>
        </property>
    </configuration>

---
