apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
    component: metastore
spec:
  selector:
    app: hive-metastore
    component: metastore
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9083
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
{{ else }}
  type: ClusterIP
{{ end }}